### ISSUE TITLE
Inserting custom image processor

### ISSUE THREAD

**Issue by at-wat** [pion/mediadevices#31]
It would be useful if a custom image processor (`func CustomImageProcessor(r video.Reader) video.Reader`) can be inserted between device and codec.

Personally, I would like to use this package as a replacement of gstreamer. Clock overlay to the image is what I want to insert by using it.

**Comment by lherman-cs** [comment]
Definitely agree. In fact, I've designed the driver and codec for this use case. What's missing right now it's just a hook in the middle between device and codec.
