### ISSUE TITLE
ScalerFastBoxSampling produces incorrect results

### ISSUE THREAD

**Issue by f-fl0** [pion/mediadevices#312]
### Your environment.
  - Version: *0.1.17*

### What did you do?

```
package main

import (
	"fmt"
	"image"
	"image/jpeg"
	"os"

	"github.com/pion/mediadevices/pkg/io/video"
)

func main() {

	inFile, _ := os.Open("image.jpg")
	defer inFile.Close()

	img, _, _ := image.Decode(inFile)
	src := video.ReaderFunc(func() (image.Image, func(), error) {
		return img, func() {}, nil
	})

	scaleFBS := video.Scale(640, 480, video.ScalerFastBoxSampling)(src)
	scaled, _, _ := scaleFBS.Read()

	outFile, _ := os.Create(fmt.Sprintf("scaled.jpg"))
	defer outFile.Close()
	jpeg.Encode(outFile, scaled, nil)
}
```
where `image.jpg` is https://upload.wikimedia.org/wikipedia/commons/d/dc/DenglerSW-Parliament-Ottawa-20050730-1280x960.jpg
	
### What did you expect?
![scaled](https://user-images.githubusercontent.com/66578286/109743469-19dc7300-7c14-11eb-91b9-5b08cfbd61bb.jpg)

### What happened?
![scaled](https://user-images.githubusercontent.com/66578286/109743302-cff38d00-7c13-11eb-89c1-898ddd7fa692.jpg)

**Comment by f-fl0** [comment]
Changing `ScalerFastBoxSampling` to `ScalerFastNearestNeighbor`, produces this image:
![scaled](https://user-images.githubusercontent.com/66578286/109753197-2c12dd00-7c25-11eb-8aad-e6ef7ee98540.jpg)

Using `ScalerFastBoxSampling` while removing the `if` condition from these lines https://github.com/pion/mediadevices/blob/b5b065369714d19004e7aedf18e8a186586b44a4/pkg/io/video/scaler_cgo.go#L158-L160 produces the same image.

**Comment by at-wat** [comment]
What is the input [YCbCrSubsampleRatio](https://golang.org/pkg/image/#YCbCrSubsampleRatio)?

**Comment by f-fl0** [comment]
> What is the input [YCbCrSubsampleRatio](https://golang.org/pkg/image/#YCbCrSubsampleRatio)?

```
	imgYCbCr := img.(*image.YCbCr)
	fmt.Println(imgYCbCr.SubsampleRatio)
	src := video.ReaderFunc(func() (image.Image, func(), error) {
		return imgYCbCr, func() {}, nil
	})
```
Print to the console: `YCbCrSubsampleRatio420` and produces the same broken outputs for both `ScalerFastBoxSampling` and `ScalerFastNearestNeighbor`.

**Comment by f-fl0** [comment]
```
scaleFBS := video.Scale(640, 480, video.ScalerFastBoxSampling)(video.ToRGBA(src))
```
Leads to the desired result.
