### ISSUE TITLE
Compile error in driver > wrapper.go

### ISSUE THREAD

**Issue by Junaid-Ahm** [pion/mediadevices#325]
This statement `uuid.NewV4().String()`  [here](https://github.com/pion/mediadevices/blob/master/pkg/driver/wrapper.go#L11) is buggy. 

The function `NewV4()` returns two values, string, error. Instead it's trying to use only the first value.

**Comment by Junaid-Ahm** [comment]
Seems to be versioning issue with go-uuid package

**Comment by lherman-cs** [comment]
@Junaid-Ahm I can't reproduce this on my machine. But, https://github.com/pion/mediadevices/pull/329 hopefully fixes this.
