### ISSUE TITLE
Optimise ToI420 conversion by using sync.Pool

### ISSUE THREAD

**Issue by EmrysMyrddin** [pion/mediadevices#424]
Since #418, the I420 conversion have been slow down because 2 new buffers are allocated for each frame converted.

The idea is to use a `sync.Pool` to minimise the overhead of creating new `[]byte`: 
 - we get a `[]byte` with `Pool.Get`, 
 - we check if it's size feats the image to convert, growing it if necessary
 - use it for the conversion
 - return the Image + a release function which calls the `Pool.Put` function with the used `[]byte` buffers.

This way we should limit the garbage collector pressure and the time needed to fill the `[]byte` with 0 values at creation.

**Comment by neversi** [comment]
Could I have a try to resolve this issue?

**Comment by neversi** [comment]
Is there need to add sync.Pool? Whenever there is the call to ReaderFunc, there is also mutex Lock, so here we could use closure instead as there is no concurrent access to the buffers.

**Comment by at-wat** [comment]
done by https://github.com/pion/mediadevices/pull/473
