### ISSUE TITLE
CI for M1 Mac

### ISSUE THREAD

**Issue by at-wat** [pion/mediadevices#434]
I'm trying Bitrise and build errors due to the broken static lib (https://github.com/pion/mediadevices/pull/428) can be reproduced.
https://app.bitrise.io/build/51dbe91e-8d3b-4a8c-a2e3-755a0d6480c3

Bitrise seems having free plan including 300 credits/month and M1 mac build takes 6 credits/run.
https://www.bitrise.io/pricing

Problems:
- the free plan doesn't have a feature to manage the repo by multiple users
- credits are belong to the user on the free plan

**Comment by edaniels** [comment]
Tried to reach out to you on the Gophers slack, but my company can sponsor this and more of pion. Let's chat there!
