### ISSUE TITLE
Add support for non-YCbCr input to ToI420

### ISSUE THREAD

**Issue by lherman-cs** [pion/mediadevices#46]
As of now, our video encoders, openh264 and vpx, only support I420 format. Therefore, we have `ToI420` converter that helps to handle any kind of image format.

However, `ToI420` can only handle YCbCr images at this moment. So, the motivation for adding more image formats would be,

1. Allow more flexibility for the input
2. Since we allow users to transform the video through `VideoTransform`, having a flexible input will also open a door for people to use a library such as https://godoc.org/github.com/disintegration/imaging, which relies highly on `NRGBA`

**Comment by at-wat** [comment]
This package seems nice: https://pkg.go.dev/golang.org/x/image/draw
https://blog.golang.org/go-imagedraw-package#TOC_6.
Scaling is also available in this package.

**Comment by lherman-cs** [comment]
That looks really cool. The package seems to be pretty flexible, I like it.
