### ISSUE TITLE
Multiple display for webcam device

### ISSUE THREAD

**Issue by SouL-H** [pion/mediadevices#510]
### Your environment.
  - Version: v0.4.0
  - Browser: Chrome Version 114.0.5735.106 
  - Other Information:   Apple Mac Mini M1 - Arm64 , another test device: Orange Pi - Ubuntu 20.04 LTS

### What did you do?
I wanted to display the webcam camera image connected to my computer on an html page.

### What did you expect?

I wanted to display the webcam image on the html page and completed it successfully. But things started when I made a request to the same link from a different tab.

### What happened?

When I made a second request I got an "invalid state: driver is already opened" error.

Here is the code where I got the error;

```go
	mediaStream, err := mediadevices.GetUserMedia(mediadevices.MediaStreamConstraints{
		Video: func(constraint *mediadevices.MediaTrackConstraints) {
			constraint.Width = prop.Int(600)
			constraint.Height = prop.Int(400)
		},
	})
	if err != nil {
		panic(err)
	}
```

Is there a function available for multiviewing or how can I solve this error?

**Comment by bazile-clyde** [comment]
Are you asking if you can open a device and stream images in two separate processes?  Linux only allows one process to open and use a device driver at a time. There are exceptions: you can query a driver's device capabilities while another process is streaming images from that same driver. But you can _not_ stream from two separate processes.

**Comment by bazile-clyde** [comment]
@SouL-H Closing for now. Feel free to reopen if this is still an issue or if I misread your question.
